version: '3.8'

services:
  db:
    image: postgres:15
    container_name: afiliado_db
    restart: always
    environment:
      POSTGRES_USER: afiliado
      POSTGRES_PASSWORD: afiliado
      POSTGRES_DB: afiliadoowner_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
