"""Create index in tabela promotions

Revision ID: 24e0c7f02dc6
Revises: aec6c6c49b6a
Create Date: 2024-12-11 10:42:48.329497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e0c7f02dc6'
down_revision: Union[str, None] = 'aec6c6c49b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_promotion_search_text', 'promotions', ['product', 'store', 'comment'], unique=False)
    op.create_index('idx_promotion_status', 'promotions', ['status'], unique=False)
    op.create_index('idx_promotion_status_created_at', 'promotions', ['status', 'created_at'], unique=False)
    op.create_index('idx_promotion_store', 'promotions', ['store'], unique=False)
    op.create_index('idx_promotion_user_id', 'promotions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_promotion_user_id', table_name='promotions')
    op.drop_index('idx_promotion_store', table_name='promotions')
    op.drop_index('idx_promotion_status_created_at', table_name='promotions')
    op.drop_index('idx_promotion_status', table_name='promotions')
    op.drop_index('idx_promotion_search_text', table_name='promotions')
    # ### end Alembic commands ###
