"""Add store in promotion

Revision ID: a549a3f65a73
Revises: 049e464f5755
Create Date: 2024-11-18 18:28:48.435767

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a549a3f65a73"
down_revision: Union[str, None] = "049e464f5755"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promotions", sa.Column("store", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promotions", "store")
    # ### end Alembic commands ###
