"""Include store and image in coupon table

Revision ID: aec6c6c49b6a
Revises: 33515e624a29
Create Date: 2024-12-03 11:47:41.943494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec6c6c49b6a'
down_revision: Union[str, None] = '33515e624a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('image', sa.String(), nullable=True))
    op.add_column('coupons', sa.Column('store', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'store')
    op.drop_column('coupons', 'image')
    # ### end Alembic commands ###
