"""Create index in tabela coupons

Revision ID: f83cb7a152c4
Revises: 24e0c7f02dc6
Create Date: 2024-12-11 10:52:24.880932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83cb7a152c4'
down_revision: Union[str, None] = '24e0c7f02dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_coupon_search_text', 'coupons', ['product', 'store', 'comment'], unique=False)
    op.create_index('idx_coupon_status', 'coupons', ['status'], unique=False)
    op.create_index('idx_coupon_status_created_at', 'coupons', ['status', 'created_at'], unique=False)
    op.create_index('idx_coupon_store', 'coupons', ['store'], unique=False)
    op.create_index('idx_coupon_user_id', 'coupons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_coupon_user_id', table_name='coupons')
    op.drop_index('idx_coupon_store', table_name='coupons')
    op.drop_index('idx_coupon_status_created_at', table_name='coupons')
    op.drop_index('idx_coupon_status', table_name='coupons')
    op.drop_index('idx_coupon_search_text', table_name='coupons')
    # ### end Alembic commands ###
